<?php

/**
 * @file
 * Contains role_change_notify.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\Core\Url;
use \Drupal\Core\Cache\Cache;

/**
 * Implements hook_help().
 */
function role_change_notify_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the role_change_notify module.
    case 'help.page.role_change_notify':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Send email to users when a new role is assigned to them.') . '</p>';
      return $output;
    // @TODO Move the complete help text from D7.

    default:
  }
}

/**
 * Implements hook_theme().
 */
function role_change_notify_theme($existing, $type, $theme, $path) {
  $themes = [];

  $themes['role_change_notify'] = [
    'variables' => [

    ],
    // Note that there is no need to indicate the template name, in absence of
    // it the system will assume "role_change_notify.html.twig", inside "templates" dir.
  ];

  return $themes;
}
